# .sync.yml
---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  os:
    - osx
  dist: '---'
  ruby_versions:
    - 2.6.3
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
  remove_branches:
    - master
  branches:
    - main
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
spec/spec_helper.rb:
  mock_with: ':rspec'
